config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'users#home', :as => :home 
  get '/signup' => 'users#signup', :as => :signup
  post '/signup' => 'users#create'
  get '/login' => 'sessions#login', :as => :login
  post '/login' => 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/home')



  resources :users

  resources :dispensers do
    resources :plants
  end


end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :dispenser
  has_one :watering
  validates :name, :location, :water_quantity, :water_frequency, presence: true
  scope :water_soon, -> {where(needs_water: 'true')}

  def self.water_today
    @todays = self.water_soon.select {|p| p.water_frequency <= p.days_left.to_i}
    @todays
  end

  def days_left
    day_string = Date.current - self.last_day_watered.to_date
    array = day_string.to_s.split("/")
    array[0]
  end

  def check_water(vacation)
    if (Date.current + vacation.to_i) >= self.next_water_day.to_date
      self.update(:needs_water => 'true')
    else
      self.update(:needs_water => 'false')
    end
  end

  def self.vacation_start(dispenser, vacation)
    dispenser.plants.each do |plant|
      @next = (Date.current + plant.water_frequency)
      plant.update(:last_day_watered => Date.current, :next_water_day => @next)
      plant.check_water(vacation)
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :require_login, :check_disp_exists, :current_user
  before_action :check_plant_exists, only: [:show, :edit, :update, :destroy]

  def index
    @plants = Plant.where(:dispenser_id => params[:dispenser_id])
    redirect_unless_logged_current
    respond_to do |f|
      f.html
      f.json {render json: @plants}
    end
  end

  def show
    redirect_unless_logged_current
    respond_to do |f|
      f.html
      f.json {render json: @plant}
    end
  end


  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.last_day_watered = Date.current
    @plant.next_water_day = (Date.current + @plant.water_frequency)
    @plant.needs_water = false
    @plant.dispenser = @dispenser
    if @plant.save
      flash[:success] = "#{@plant.name} has been successfully created."
      redirect_to dispensers_path(@dispenser)
    else
      error_messages(@plant)
      render :new
    end
  end

  def edit
  end

  def update
    if @plant.update(:name => params[:plant][:name], :location => params[:plant][:location], :water_quantity => params[:plant][:water_quantity], :water_frequency => params[:plant][:water_frequency])
      flash[:success] = "#{@plant.name} has been successfully updated."
      redirect_to dispensers_path(@plant.dispenser)
    else
      error_messages(@plant)
      return redirect_to edit_dispenser_plant_path(@plant.dispenser, @plant)
    end
  end

  def destroy
    name = @plant.name
    @plant.destroy
    flash[:success] = "#{name} has been successfully deleted."
    redirect_to dispensers_path(@plant.dispenser)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :location, :water_quantity, :water_frequency)
  end

  def check_disp_exists
    unless @dispenser = Dispenser.find_by_id(params[:dispenser_id])
      redirect_to home_path
    end
  end

  def check_plant_exists
    unless @plant = Plant.find_by_id(params[:id])
      redirect_to home_path
    end
  end

end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/edit.html.erb
<div class="background editplantb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <div class="center">
    <h1>Edit This Plant</h1>
    <%= form_for(@plant, url: dispenser_plant_path(@plant.dispenser, @plant), method: :patch) do |f| %>
      Name: <%= f.text_field :name, placeholder: @plant.name %>
      <br>
      Location: <%= f.text_field :location, placeholder: @plant.location %>
      <br>
      Water Quantity (oz): <%= f.select :water_quantity, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36'], placeholder: @plant.water_quantity %>
      <br>
      Water Frequency (days): <%= f.select :water_frequency, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31'], placeholder: @plant.water_frequency %>
      <br>
      <%= f.submit "Submit" %>
    <% end %>

    <p class="bold">- or -</p>

    <%= form_for(@plant, url: dispenser_plant_path(@plant.dispenser, @plant), method: :delete) do |f| %>
      <%= f.submit "Delete this plant" %>
    <% end %>
  </div>
</div>

app/views/plants/index.html.erb
<div class="background plantindexb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <div class="center">
    <h1><%= @dispenser.name %></h1>

    <button class="rename-add"><%= link_to("Edit Can", edit_dispenser_path(@dispenser)) %></button>
    <button class="rename-add"><%= link_to("Add a plant", new_dispenser_plant_path(@dispenser)) %></button>
  </div>
  <br>
  <div class="section shadow scroll_box">
    <ol>
      <% @dispenser.plants.each do |plant| %>
      <li class="yeseva"><%= link_to plant.name, edit_dispenser_plant_path(@dispenser, plant), :class => "plantlink" %> - <%= plant.location %></li>
      <ul>
        <li>Water <%= plant.water_quantity %>oz, every <%= plant.water_frequency %> day(s)</li>
        <% unless plant.next_water_day.blank? && plant.last_day_watered.blank? %>
        <li>Last day watered: <%= plant.last_day_watered.to_date.strftime("%m/%d/%Y") %>, Next water day: <%= plant.next_water_day.to_date.strftime("%m/%d/%Y") %></li>
        <% end %>
      </ul>
      <% end %>
    </ol>
  </div>
</div>

app/views/plants/new.html.erb
<div class="background newplantb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <div class="center">
    <h1>Add a New Plant</h1>
    <%= form_for @plant, url: dispenser_plants_path(@dispenser) do |f| %>
      Name: <%= f.text_field :name %>
      <br>
      Location: <%= f.text_field :location %>
      <br>
      Water Quantity (oz): <%= f.select :water_quantity, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36'] %>
      <br>
      Water Frequency (days): <%= f.select :water_frequency, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31'] %>
      <br>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/plants/show.html.erb
<div class="background plantindexb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <div class="center">
    <h1><%= @plant.name %></h1>
  </div>
  <br>
  <div class="section shadow scroll_box">

      <ul>
        <li>Water <%= @plant.water_quantity %>oz, every <%= @plant.water_frequency %> day(s)</li>
        <% unless @plant.next_water_day.blank? && @plant.last_day_watered.blank? %>
        <li>Last day watered: <%= @plant.last_day_watered.to_date.strftime("%m/%d/%Y") %>, Next water day: <%= @plant.next_water_day.to_date.strftime("%m/%d/%Y") %></li>
        <% end %>
      </ul>

  </div>
</div>