config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'users#home', :as => :home 
  get '/signup' => 'users#signup', :as => :signup
  post '/signup' => 'users#create'
  get '/login' => 'sessions#login', :as => :login
  post '/login' => 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/home')



  resources :users

  resources :dispensers do
    resources :plants
  end


end

app/models/dispenser.rb
class Dispenser < ApplicationRecord
  belongs_to :user
  has_many :plants
  validates :name, :product_number, :capacity, presence: true
  validates :product_number, uniqueness: true
  validates :vacation_days, numericality: { greater_than_or_equal_to: 0 }

  def vacation_over?
    Plant.water_soon.where(:dispenser_id => self.id).empty?
  end

  def see_amount(plant)
    if plant.water_quantity > self.current_amount
      the_leftover = plant.water_quantity - self.current_amount
      self.update(:current_amount => (self.capacity - the_leftover), :date_refilled => Date.current)
    else
      self.update(:current_amount => (self.capacity - plant.water_quantity))
    end
  end

  def water
    if @plants = Plant.water_today.select {|p| p.dispenser == self}
      @plants.each do |plant|
        @days_array = (self.end_vacation.to_date - Date.current).to_s.split("/")
        self.update(:vacation_days => @days_array[0].to_i)
        self.see_amount(plant)
        plant.update(:last_day_watered => Date.current, :next_water_day => (Date.current + plant.water_frequency))
        plant.check_water(self.vacation_days)
      end
    end
  end
end

app/controllers/dispensers_controller.rb
class DispensersController < ApplicationController
  before_action :require_login, :current_user
  before_action :check_d_exists, except: [:index, :new, :create]

  def index
    @dispensers = @user.dispensers
  end

  def new
    @dispenser = Dispenser.new
  end

  def create
    @dispenser = Dispenser.new(dispenser_params)
    @dispenser.vacation_days = 0
    @dispenser.user = @user
    if @dispenser.save
      @dispenser.update(:date_refilled => Date.current, :current_amount => 0, :start_vacation => (Date.current - 1), :end_vacation => (Date.current - 1))
      flash[:success] = "#{@dispenser.name} has been successfully registered."
      redirect_to dispensers_path(@dispenser)
    else
      error_messages(@dispenser)
      render :new
    end
  end

  def edit
    respond_to do |f|
      f.html
      f.json {render json: @dispenser}
    end
  end

  def update
    if @dispenser.update(:name => params[:dispenser][:name])
      flash[:success] = "#{@dispenser.name} has been successfully updated."
      respond_to do |f|
        f.html {redirect_to dispensers_path(@dispenser)}
        f.json {render json: @dispenser}
      end
    else
      error_messages(@dispenser)
      return redirect_to edit_dispenser_path(@dispenser)
    end
  end

  def destroy
    name = @dispenser.name
    @dispenser.destroy
    flash[:success] = "#{name} has been successfully deleted."
    redirect_to dispensers_path
  end


  private

  def dispenser_params
    params.require(:dispenser).permit(:name, :product_number, :capacity)
  end

  def check_d_exists
    unless @dispenser = Dispenser.find_by_id(params[:id])
      redirect_to home_path
    end
  end
end

app/helpers/dispensers_helper.rb
module DispensersHelper
end

app/views/dispensers/edit.html.erb
<div class="background editdispb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <div class="center">
    <h1>Rename This Watering Can</h1>
    <%= form_for(@dispenser, url: dispenser_path(@dispenser), method: :patch) do |f| %>
      <%= f.text_field :name, placeholder: @dispenser.name %>
      <%= f.submit "Rename Can" %>
    <% end %>

    <p class="bold">- or -</p>

    <%= form_for(@dispenser, url: dispenser_path(@dispenser), method: :delete) do |f| %>
      <%= f.submit "Delete This Watering Can" %>
    <% end %>
  </div>
</div>

app/views/dispensers/index.html.erb
<div class="background dispindexb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <h1 class="center">My Watering Cans</h1>
  <p class="center yeseva">Click on a Can to edit or add plants</p>
  <br>
  <div class="scroll_box">
    <% @dispensers.each do |disp| %>

    <div class="section shadow">
      <div id='<%= disp.id %>-name-container'>
        <h2><%= link_to disp.name, edit_dispenser_path(disp), :class => "disp-font disp-name-edit", :data_id => disp.id %></h2>
      </div>
      <ol class="yeseva">
        <div class="list-container" id=<%= disp.id %>>
          <li><%= link_to "See Plants", dispenser_plants_path(disp), :class => "all_plants", :data_id => disp.id %></li>
        </div>

      </ol>
      <button class="rename-add"><%= link_to("Add a plant", new_dispenser_plant_path(disp)) %></button>
      <button class="rename-add" id="upsize"><%= link_to "Delete dispenser", dispenser_path(disp), :method => :delete %></button>

    </div>
    <% end %>
  </div>
</div>

app/views/dispensers/new.html.erb
<div class="background newdispb">
  <%= render partial: "navbar" %>
  <br><br><br>
  <h1 class="center">Register a New Can</h1>
  <br>
  <div class="center yeseva">
    <%= form_for @dispenser, url: dispensers_path do |f| %>
      Name: <%= f.text_field :name %>
      <br>
      Product Number: <%= f.text_field :product_number %>
      <br>
      Capacity (oz): <%= f.select :capacity, ['24', '36', '48'] %>
      <%= f.submit "Register" %>
    <% end %>
  </div>
</div>