config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'users#home', :as => :home 
  get '/signup' => 'users#signup', :as => :signup
  post '/signup' => 'users#create'
  get '/login' => 'sessions#login', :as => :login
  post '/login' => 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/home')



  resources :users

  resources :dispensers do
    resources :plants
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper

  def logged_in?
    !!session[:user_id]
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @user = User.find_by_id(session[:user_id])
  end

  def logged_in_or_redirect
    if logged_in?
      @user = current_user
      redirect_to user_path(@user)
    end
  end

  def redirect_unless_logged_current
    unless logged_in? && @user == current_user
      flash[:error] = "You must be signed up and logged in to access this section"
      redirect_to home_path
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to home_path
    end
  end

  def error_messages(thing)
    @errors = thing.errors.full_messages.map {|error| error << ". " }
    flash[:error] = @errors.join("")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<% if flash[:notice] || flash[:success] || flash[:error] %>
  <nav class="nav flash-active site-wrapper--padding">
<% else %>
  <nav class="nav site-wrapper--padding">
<% end %>

  <% if flash[:notice] %>
    <div class="notice flash-bar col flex-container site-wrapper--padding">
      <p class="flash-type col col--full col--center"><%= flash[:notice] %></p>
    </div>
  <% elsif flash[:error] %>
    <div class="error flash-bar col flex-container site-wrapper--padding">
      <p class="flash-type col col--full col--center"><%= flash[:error] %></p>
    </div>
  <% elsif flash[:success] %>
    <div class="success flash-bar col flex-container site-wrapper--padding">
      <p class="flash-type col col--full col--center"><%= flash[:success] %></p>
    </div>
  <% end %>

    <div class="flex-container col--v-center">
      <div class="dropdown">
        <button class="dropbtn">
          <div class="burger-line"></div>
          <div class="burger-line"></div>
          <div class="burger-line"></div>
        </button>
        <div class="dropdown-content">
          <%= link_to("Account", user_path(@user)) %>
          <%= link_to "My Watering Cans", dispensers_path, class: "all_dispensers" %>
          <%= link_to("Register A New Can", new_dispenser_path) %>
        </div>
      </div>

      <p class="col col--full2 col--center logo_container logo-font">
        <%= link_to("Watering Can", home_path, :class => "logo") %></p>

        <div class="col col--right nav-end-link">
          <%= link_to('Log Out', logout_path) %>
        </div>
    </div>
  </nav>

app/views/application/_navbarlogin.html.erb
<% if flash[:notice] || flash[:success] || flash[:error] %>
  <nav class="nav flash-active site-wrapper--padding">
<% else %>
  <nav class="nav site-wrapper--padding">
<% end %>


<% if flash[:error] %>
  <div class="error flash-bar col flex-container site-wrapper--padding">
    <p class="flash-type col col--full col--center"><%= flash[:error] %></p>
  </div>
<% end %>
<% if flash[:success] %>
  <div class="success flash-bar col flex-container site-wrapper--padding">
    <p class="flash-type col col--full col--center"><%= flash[:success] %></p>
  </div>
<% end %>

<div class="flex-container col--v-center">
  <div class="dropdown">
    <button class="dropbtn">
      <div class="burger-line"></div>
      <div class="burger-line"></div>
      <div class="burger-line"></div>
    </button>
    <div class="dropdown-content">
      <%= link_to("Log In", login_path) %>
      <%= link_to("Sign Up", signup_path) %>
    </div>
  </div>

  <p class="col col--full2 col--center logo_container logo-font">
    <%= link_to("Watering Can", home_path, :class => "logo") %></p>

    <div class="col col--right nav-end-link">
      <%= link_to('Log In', login_path) %>
    </div>
</div>
</nav>